name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: guardian/actions-setup-node@main
      - uses: bahmutov/npm-install@v1
      - run: ./script/build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: guardian/actions-setup-node@main
      - uses: bahmutov/npm-install@v1
      - run: ./script/lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: guardian/actions-setup-node@main
      - uses: bahmutov/npm-install@v1
      - run: ./script/test
