name: PR
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-release:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
